server:
  servlet:
    context-path: /shapes

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

flyway:
  url: jdbc:h2:mem:testdb
  schemas: SHAPES
  user: sa
  password: 